# write a set instruction

#give us to node inage for our project
FROM node:latest

#Here we dont copy into the ./app directory of the image to do so
# WORKDIR /app
# COPY ./app dest

#copy the whole files code into the image
COPY . .

#run or install the modules of our project like here we have a express
#you can also do as RUN npm install
RUN npm i

#open the port  mention the port number that you enter at the time of the writting the program
EXPOSE 8800

# Run the code
CMD [ "node","index.js" ]

#to Run the created docker imager
# docker build -t basic-app .      //-t for giving the tag  i.e. desire app name   also you do to run  docker run basic-app
# go to the docker desktop
# go to continer 
# click on the play button of the container assign desire port number(if we give 0 it allocat the random port and it will benefial for us )
# n all and run the container
# images are like the class of the java nad container like the object ,we can create as many as object i.e. container of the image


# we all do is for 
# To avoid the version udatation ,to avoid the system error "We create the Docker image.." and creating the image we run our project any
# where without fear

# To delete the image
# docker image rm image-nm   //o/p as untagged  deleted 
# docker image rm image-nm -f

# To removw the all the images and the comtainer 
# docker system prune -a

